# Generated by Django 3.2.3 on 2021-05-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_scratchers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backscratchers',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='backscratchers',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
