# Generated by Django 3.2.3 on 2021-05-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_scratchers', '0002_auto_20210520_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backscratchers',
            name='size',
        ),
        migrations.AddField(
            model_name='backscratchers',
            name='size',
            field=models.ManyToManyField(to='back_scratchers.Size'),
        ),
    ]
